// ======================== TIMELINE DATA ========================
const timelineData = [
  { step: 1, title: "Delimitation of Constituencies", icon: "🗺️", date: "Years before election", desc: "The Delimitation Commission redraws constituency boundaries based on the latest Census data to ensure equal representation. India is divided into 543 Lok Sabha and ~4,000+ Vidhan Sabha constituencies." },
  { step: 2, title: "Electoral Roll Preparation", icon: "📋", date: "Months before election", desc: "The Election Commission prepares and revises the electoral rolls (voter lists). Citizens aged 18+ can register using Form 6 online or offline. Special drives are conducted to maximize enrollment." },
  { step: 3, title: "Announcement of Election Schedule", icon: "📢", date: "~6-8 weeks before polling", desc: "The Election Commission announces dates for nominations, scrutiny, withdrawal, and polling. The Model Code of Conduct (MCC) comes into effect immediately, restricting government announcements and transfers." },
  { step: 4, title: "Nomination of Candidates", icon: "📝", date: "~4-5 weeks before polling", desc: "Candidates file nomination papers with the Returning Officer. They must deposit ₹25,000 (General) or ₹12,500 (SC/ST) for Lok Sabha. Independent candidates and party nominees both participate." },
  { step: 5, title: "Scrutiny of Nominations", icon: "🔍", date: "After nomination deadline", desc: "The Returning Officer examines all nomination papers for validity — checking age, citizenship, disqualifications, and proper documentation. Invalid nominations are rejected." },
  { step: 6, title: "Withdrawal of Candidature", icon: "🔙", date: "2 days after scrutiny", desc: "Candidates may withdraw their nominations before the deadline. After withdrawal, the final list of contesting candidates is published and allotted symbols by the ECI." },
  { step: 7, title: "Election Campaigning", icon: "📣", date: "Until 48 hrs before polling", desc: "Parties and candidates campaign through rallies, advertisements, social media, and door-to-door canvassing. Campaigning must stop 48 hours before polling day. Expenditure limits are strictly monitored." },
  { step: 8, title: "Polling Day", icon: "🗳️", date: "Scheduled polling date(s)", desc: "Voters cast their votes using Electronic Voting Machines (EVMs) at designated polling booths. Voter identity is verified via EPIC (Voter ID) or approved alternatives. VVPAT machines provide a paper trail." },
  { step: 9, title: "Counting of Votes", icon: "🔢", date: "Usually 3-4 days after final phase", desc: "EVMs are stored securely and opened for counting on the designated date. Postal ballots are counted first, then EVM votes round by round. VVPAT slips of 5 random booths per constituency are verified." },
  { step: 10, title: "Declaration of Results", icon: "🏆", date: "Same day as counting", desc: "The Returning Officer declares the winning candidate. Results are published on the ECI website. The party/alliance with majority (272+ in Lok Sabha) is invited to form the government." }
];

// ======================== FLASHCARD DATA ========================
const flashcardData = [
  { front: "EVM", back: "Electronic Voting Machine — A portable, battery-operated device used in Indian elections since 2004 (nationwide). It has a Ballot Unit and a Control Unit, storing up to 64 candidates." },
  { front: "VVPAT", back: "Voter Verifiable Paper Audit Trail — Attached to EVMs, it prints a slip showing the candidate name and symbol, visible for 7 seconds, then drops into a sealed box for verification." },
  { front: "ECI", back: "Election Commission of India — An autonomous constitutional body (Article 324) responsible for conducting free and fair elections. Led by the Chief Election Commissioner and Election Commissioners." },
  { front: "MCC", back: "Model Code of Conduct — A set of guidelines issued by ECI for political parties and candidates during elections. It regulates speeches, rallies, polling day conduct, and government machinery use." },
  { front: "NOTA", back: "None Of The Above — An option on the EVM allowing voters to reject all candidates. Introduced in 2013 following the Supreme Court's ruling in PUCL vs Union of India." },
  { front: "EPIC", back: "Electors Photo Identity Card — Also known as Voter ID card, issued by ECI to all eligible voters. It serves as identity proof at polling stations. Contains photo, name, age, and constituency." },
  { front: "Lok Sabha", back: "The Lower House of Parliament (House of the People). Has 543 elected members + 2 nominated Anglo-Indian members (until 2020). Members are elected by direct vote for 5-year terms." },
  { front: "Rajya Sabha", back: "The Upper House of Parliament (Council of States). Has 245 members — 233 elected by state legislatures and 12 nominated by the President. Members serve 6-year terms with 1/3 retiring every 2 years." },
  { front: "FPTP", back: "First Past The Post — The electoral system used in India where the candidate with the most votes in a constituency wins, regardless of whether they secure a majority (50%+)." },
  { front: "Anti-Defection Law", back: "The 52nd Amendment (1985) added the Tenth Schedule to the Constitution. It disqualifies legislators who voluntarily give up party membership or vote against party whip." },
  { front: "Delimitation", back: "The process of redrawing constituency boundaries to ensure roughly equal population per seat. Done by the Delimitation Commission, last major exercise based on 2001 Census." },
  { front: "Electoral Bond", back: "A financial instrument introduced in 2018 for making anonymous donations to political parties. Declared unconstitutional by the Supreme Court in February 2024." },
  { front: "Article 324", back: "The constitutional provision that vests the superintendence, direction, and control of elections in the Election Commission of India, giving it broad powers." },
  { front: "Returning Officer", back: "A government official appointed by ECI to oversee elections in a specific constituency — responsible for nominations, polling, counting, and declaring results." },
  { front: "Form 6", back: "The application form used to register as a new voter in India. Can be filed online via the National Voter Service Portal (NVSP) or offline at the local ERO office." },
  { front: "Panchayat Elections", back: "Local body elections for rural governance conducted by State Election Commissions. The three tiers are Gram Panchayat, Panchayat Samiti (Block), and Zila Parishad (District)." },
  { front: "Voter Turnout", back: "The percentage of registered voters who actually cast their vote. India's 2024 General Election saw ~65.8% turnout. The highest ever was 67.4% in 2014." },
  { front: "Election Symbols", back: "Visual identifiers allotted to political parties by ECI. National parties get a permanent symbol across India. State parties get symbols within their state. Independents are allotted 'free' symbols." },
  { front: "Postal Ballot", back: "A method allowing certain voters (armed forces, government on duty, seniors 80+, PwD, COVID patients) to vote by mail instead of visiting a polling booth." },
  { front: "State Election Commission", back: "A constitutional body (Article 243K) that conducts elections for Panchayats and Municipalities within each state, independent of the Election Commission of India." }
];

// ======================== QUIZ DATA ========================
const quizData = [
  { q: "How many seats are there in the Lok Sabha?", options: ["245", "543", "552", "250"], answer: 1 },
  { q: "What is the minimum voting age in India?", options: ["21 years", "16 years", "18 years", "25 years"], answer: 2 },
  { q: "Who appoints the Chief Election Commissioner of India?", options: ["Prime Minister", "Chief Justice", "President of India", "Vice President"], answer: 2 },
  { q: "When was NOTA introduced in Indian elections?", options: ["2009", "2013", "2015", "2010"], answer: 1 },
  { q: "What does VVPAT stand for?", options: ["Voter Verified Paper Audit Trail", "Voter Verifiable Paper Audit Trail", "Vote Verification Paper Audit Tool", "Voter Valid Paper Authentication Trail"], answer: 1 },
  { q: "Which article of the Constitution deals with the Election Commission?", options: ["Article 280", "Article 370", "Article 324", "Article 356"], answer: 2 },
  { q: "What electoral system does India use for Lok Sabha elections?", options: ["Proportional Representation", "First Past The Post", "Mixed Member", "Single Transferable Vote"], answer: 1 },
  { q: "How long is the term of a Rajya Sabha member?", options: ["5 years", "4 years", "6 years", "Life"], answer: 2 },
  { q: "When must election campaigning stop before polling day?", options: ["24 hours", "48 hours", "72 hours", "12 hours"], answer: 1 },
  { q: "What is the security deposit for a Lok Sabha candidate (General category)?", options: ["₹10,000", "₹50,000", "₹25,000", "₹1,00,000"], answer: 2 },
  { q: "Which amendment introduced the Anti-Defection Law?", options: ["42nd", "44th", "52nd", "61st"], answer: 2 },
  { q: "How many members does the President nominate to the Rajya Sabha?", options: ["2", "10", "12", "14"], answer: 2 },
  { q: "What form is used to register as a new voter?", options: ["Form 2", "Form 6", "Form 8", "Form 10"], answer: 1 },
  { q: "Which body conducts Panchayat elections?", options: ["Election Commission of India", "State Election Commission", "District Collector", "Governor"], answer: 1 },
  { q: "In which year were EVMs used nationwide for the first time?", options: ["1999", "2002", "2004", "2009"], answer: 2 }
];

// ======================== INFO DATA ========================
const infoData = {
  types: {
    title: "Types of Elections in India",
    content: [
      { heading: "General Elections (Lok Sabha)", text: "Held every 5 years to elect 543 members of the Lok Sabha. All Indian citizens aged 18+ can vote. The party/alliance winning 272+ seats forms the government. The PM is the leader of the majority party." },
      { heading: "State Assembly Elections (Vidhan Sabha)", text: "Conducted for each state's legislative assembly. The number of seats varies by state (e.g., UP has 403, Goa has 40). The winning party's leader becomes the Chief Minister." },
      { heading: "Rajya Sabha Elections", text: "Members are elected by elected members of State Legislative Assemblies using the Single Transferable Vote system. 1/3 of members retire every 2 years. No direct public voting." },
      { heading: "Local Body Elections", text: "Panchayat (rural) and Municipal (urban) elections are conducted by State Election Commissions. These include Gram Panchayat, Block Panchayat, Zila Parishad, Municipal Corporations, and Nagar Panchayats." },
      { heading: "By-Elections", text: "Held to fill vacancies caused by death, resignation, or disqualification of a sitting member. Conducted only for the specific constituency." },
      { heading: "Presidential & Vice-Presidential Elections", text: "The President is elected by an Electoral College comprising elected MPs and MLAs. The Vice-President is elected by members of both Houses of Parliament." }
    ]
  },
  bodies: {
    title: "Constitutional & Electoral Bodies",
    content: [
      { heading: "Election Commission of India (ECI)", text: "Established on 25 Jan 1950 under Article 324. An autonomous body that supervises elections to Parliament, State Legislatures, and offices of President and Vice-President. Led by CEC and Election Commissioners." },
      { heading: "Chief Election Commissioner (CEC)", text: "Head of the ECI with security of tenure similar to a Supreme Court judge. Can only be removed through impeachment. Recent CEC Appointment Act 2023 changed the selection process." },
      { heading: "State Election Commissions", text: "Article 243K establishes SECs for conducting Panchayat and Municipal elections. The State Election Commissioner is appointed by the Governor." },
      { heading: "Delimitation Commission", text: "A high-powered body established by Parliament to redraw constituency boundaries. Headed by a retired Supreme Court judge. Its orders have the force of law and cannot be challenged in court." },
      { heading: "Returning Officer (RO)", text: "Appointed by ECI for each constituency to manage the election process — from nomination to result declaration. Usually a senior district-level officer." },
      { heading: "Election Observers", text: "ECI appoints General Observers, Expenditure Observers, and Police Observers for each constituency to ensure free and fair elections and monitor code violations." }
    ]
  },
  voting: {
    title: "The Voting Process",
    content: [
      { heading: "Voter Registration", text: "Citizens aged 18+ on Jan 1 of the qualifying year can register online via NVSP portal or by submitting Form 6 to the Electoral Registration Officer. NRI voters can register under Section 20A." },
      { heading: "Voter ID (EPIC)", text: "After registration, voters receive an Elector's Photo Identity Card. Alternatively, 12 other ID documents (Aadhaar, Passport, etc.) are accepted at polling booths." },
      { heading: "At the Polling Booth", text: "Voters visit their assigned booth, get identity verified, receive indelible ink mark on left index finger, then use the EVM to cast their vote. The VVPAT slip confirms the choice." },
      { heading: "EVM & VVPAT Process", text: "The Ballot Unit displays candidate names/symbols. Voter presses the button next to their choice. VVPAT prints a slip visible for 7 seconds. The vote is stored electronically in the Control Unit." },
      { heading: "Postal & Absentee Voting", text: "Service voters (armed forces), government officials on election duty, seniors (80+), PwD voters, and essential service workers can use postal ballots. Electronically Transmitted Postal Ballot System (ETPBS) is used for service voters." },
      { heading: "NOTA Option", text: "Since 2013, voters can choose 'None Of The Above' if they don't wish to vote for any candidate. NOTA votes are counted but don't affect the result — the candidate with the most votes still wins." }
    ]
  },
  history: {
    title: "Key Milestones in Indian Elections",
    content: [
      { heading: "1951-52: First General Election", text: "The world's largest democratic exercise at the time. 17.3 crore voters, 53% turnout. Jawaharlal Nehru's INC won 364 of 489 seats. Sukumar Sen was the first Chief Election Commissioner." },
      { heading: "1989: Voting Age Lowered to 18", text: "The 61st Constitutional Amendment reduced the voting age from 21 to 18, bringing millions of young voters into the democratic process." },
      { heading: "1993: Panchayati Raj Elections Mandated", text: "The 73rd and 74th Amendments made elections to local bodies (Panchayats and Municipalities) constitutionally mandatory with reserved seats for SC/ST and women." },
      { heading: "2004: Nationwide EVM Usage", text: "EVMs replaced paper ballots entirely across all constituencies, making India one of the first countries to fully adopt electronic voting." },
      { heading: "2013: NOTA Introduced", text: "Following the PUCL vs Union of India verdict, the Supreme Court directed ECI to include a NOTA button on EVMs, empowering voters to reject all candidates." },
      { heading: "2024: Largest Election Ever", text: "India's 18th Lok Sabha election: 96.8 crore eligible voters, conducted in 7 phases over 44 days. Over 10.5 lakh polling stations were set up across the country." }
    ]
  }
};

// ======================== ASSISTANT KNOWLEDGE BASE ========================
const assistantKB = [
  { keywords: ["register", "vote", "voter id", "enroll", "registration", "form 6", "nvsp"], answer: "To register as a voter in India:\n\n1. **Online**: Visit the National Voter Service Portal (voters.eci.gov.in) and fill Form 6\n2. **Offline**: Visit your local Electoral Registration Officer (ERO) with Form 6, proof of age, address proof, and a passport photo\n3. **Eligibility**: You must be an Indian citizen aged 18+ on January 1 of the qualifying year\n4. **NRIs**: Can register under Section 20A of the RP Act\n\nAfter verification, you'll receive your EPIC (Voter ID card)." },
  { keywords: ["evm", "electronic voting", "voting machine"], answer: "**Electronic Voting Machine (EVM)**:\n\n• Used nationwide since 2004, replacing paper ballots\n• Has two units: **Ballot Unit** (for voters) and **Control Unit** (with polling officer)\n• Battery-operated, no internet connection — cannot be hacked remotely\n• Stores up to 64 candidates per machine\n• Each press registers only ONE vote\n• EVMs are manufactured by BEL (Bharat Electronics) and ECIL\n• Machines undergo multiple rounds of testing and randomization before deployment" },
  { keywords: ["nota", "none of the above", "reject"], answer: "**NOTA (None Of The Above)**:\n\n• Introduced in 2013 after the Supreme Court ruling in PUCL vs Union of India\n• Allows voters to officially reject all candidates\n• NOTA is the last button on the EVM\n• However, NOTA votes don't affect results — even if NOTA gets the highest votes, the candidate with the next highest wins\n• In the 2024 elections, NOTA received over 65 lakh votes nationally" },
  { keywords: ["lok sabha", "parliament", "lower house", "seats", "543"], answer: "**Lok Sabha (House of the People)**:\n\n• Lower House of India's Parliament\n• **543 elected members** from single-member constituencies\n• Members elected by direct vote using FPTP system\n• Term: 5 years (can be dissolved earlier)\n• 84 seats reserved for SC, 47 for ST communities\n• A party/alliance needs **272 seats** for a majority\n• The PM is the leader of the majority party/alliance" },
  { keywords: ["rajya sabha", "upper house", "council of states"], answer: "**Rajya Sabha (Council of States)**:\n\n• Upper House of India's Parliament\n• **245 members**: 233 elected + 12 nominated by the President\n• Elected by MLAs of State Assemblies using Single Transferable Vote\n• Members serve **6-year terms**, with 1/3 retiring every 2 years\n• It is a permanent body — it cannot be dissolved\n• The Vice-President is the ex-officio Chairman" },
  { keywords: ["vvpat", "paper trail", "paper audit"], answer: "**VVPAT (Voter Verifiable Paper Audit Trail)**:\n\n• Attached to EVMs since 2017 (mandatory nationwide)\n• When a voter presses a button, a paper slip is printed showing the candidate's name, serial number, and symbol\n• The slip is visible for **7 seconds** through a transparent window\n• It then drops into a sealed box\n• In counting, VVPAT slips of **5 randomly selected booths** per constituency are matched with EVM results\n• Provides an independent verification mechanism" },
  { keywords: ["mcc", "model code", "code of conduct"], answer: "**Model Code of Conduct (MCC)**:\n\n• Comes into effect from the date election schedule is announced\n• Key rules:\n  - No new government schemes/projects can be announced\n  - No use of official machinery for campaigning\n  - No appeals on communal or caste lines\n  - Campaign must stop 48 hours before polling\n  - No distribution of liquor, cash, or gifts\n• Enforced by ECI through observers and flying squads\n• While not legally enforceable per se, violations can lead to FIRs and ECI action" },
  { keywords: ["eci", "election commission", "commissioner", "article 324"], answer: "**Election Commission of India (ECI)**:\n\n• Constitutional body under **Article 324**\n• Established on **25 January 1950** (celebrated as National Voters' Day)\n• Comprises: Chief Election Commissioner (CEC) + Election Commissioners\n• CEC can only be removed by Parliament (similar to SC judge impeachment)\n• Powers: Conduct elections, prepare electoral rolls, allot symbols, enforce MCC, settle election disputes\n• Functions independently of the government" },
  { keywords: ["anti-defection", "defection", "party switch", "tenth schedule"], answer: "**Anti-Defection Law (52nd Amendment, 1985)**:\n\n• Added the **Tenth Schedule** to the Constitution\n• A legislator is disqualified if they:\n  - Voluntarily give up party membership\n  - Vote against party whip on confidence/no-confidence motions\n• **Exception**: If at least 2/3 of the party's legislators merge with another party\n• The Speaker/Chairman decides disqualification petitions\n• Aims to prevent political horse-trading and ensure government stability" },
  { keywords: ["electoral bond", "donation", "funding", "party fund"], answer: "**Electoral Bonds**:\n\n• Introduced in 2018 as anonymous financial instruments for political donations\n• Available in denominations of ₹1,000 to ₹1 crore\n• Purchased from State Bank of India, valid for 15 days\n• **Struck down** by the Supreme Court in **February 2024** as unconstitutional\n• The Court ruled they violated citizens' right to information about political funding\n• SBI was ordered to disclose all bond purchase and encashment details to ECI" },
  { keywords: ["panchayat", "local body", "gram", "municipal", "urban", "rural"], answer: "**Local Body Elections**:\n\n• **Rural**: Gram Panchayat → Panchayat Samiti (Block) → Zila Parishad (District)\n• **Urban**: Nagar Panchayat → Municipal Council → Municipal Corporation\n• Mandated by the **73rd & 74th Amendments** (1993)\n• Conducted by **State Election Commissions** (not ECI)\n• **Reservation**: 1/3 seats reserved for women; seats reserved for SC/ST based on population\n• The Sarpanch/Mayor is the elected head of rural/urban local bodies" },
  { keywords: ["delimitation", "constituency", "boundary", "seats allocation"], answer: "**Delimitation**:\n\n• The process of redrawing electoral constituency boundaries\n• Done by the **Delimitation Commission** (headed by a retired SC judge)\n• Purpose: Ensure roughly equal population per constituency\n• Last major exercise: Based on **2001 Census** (Delimitation Act 2002)\n• Delimitation orders have the force of law — **cannot be challenged in court**\n• A new delimitation based on the upcoming Census is expected after 2026" },
  { keywords: ["president", "presidential election", "electoral college"], answer: "**Presidential Election**:\n\n• The President is elected by an **Electoral College** comprising:\n  - Elected MPs of both Houses of Parliament\n  - Elected MLAs of all State Assemblies & UTs with legislatures\n• Uses **Single Transferable Vote** with proportional representation\n• Value of each MLA/MP vote is calculated based on state population\n• The President serves a **5-year term** and can be re-elected\n• Candidates need 50 electors as proposers and 50 as seconders" },
  { keywords: ["how many", "phases", "general election", "2024", "schedule"], answer: "**General Election Schedule (2024 Example)**:\n\n• India's 18th Lok Sabha Election was held in **7 phases**\n• Phase 1: April 19 → Phase 7: June 1, 2024\n• Results declared: **June 4, 2024**\n• **96.8 crore** eligible voters\n• **10.5 lakh+** polling stations\n• **1.5 crore** election officials deployed\n• Multi-phase voting is necessary due to security force deployment and India's vast geography" },
  { keywords: ["who can contest", "eligibility", "candidate", "age", "qualification"], answer: "**Candidate Eligibility**:\n\n• **Lok Sabha**: Indian citizen, minimum age **25 years**\n• **Rajya Sabha**: Indian citizen, minimum age **30 years**\n• **State Assembly**: Indian citizen, minimum age **25 years**\n• Must be registered as a voter in any constituency in India\n• **Disqualifications**: Holding office of profit, unsound mind, undischarged insolvent, non-citizen, convicted with 2+ year sentence\n• **No educational qualification** is required to contest elections" },
  { keywords: ["history", "first election", "1952", "milestone"], answer: "**Key Milestones**:\n\n• **1951-52**: First General Election — 17.3 crore voters, 53% turnout\n• **1989**: Voting age lowered from 21 to 18 (61st Amendment)\n• **1993**: 73rd/74th Amendments mandated local body elections\n• **2003**: Postal ballots introduced for service voters\n• **2004**: EVMs used nationwide\n• **2013**: NOTA introduced\n• **2014**: Highest ever turnout — 67.4%\n• **2017**: VVPAT mandatory nationwide\n• **2024**: Largest election in history — 96.8 crore voters" },
  { keywords: ["complete process", "election process", "step by step", "how election works", "start to end", "full process"], answer: "**Complete Indian Election Process (Start to End)**:\n\n**Phase 1 — Preparation**\n1. 🗺️ **Delimitation**: Constituency boundaries redrawn based on Census\n2. 📋 **Electoral Roll**: Voter lists prepared/revised by ECI\n\n**Phase 2 — Announcement**\n3. 📢 **Schedule Declared**: ECI announces dates; MCC kicks in immediately\n\n**Phase 3 — Nominations**\n4. 📝 **Filing**: Candidates submit papers + security deposit\n5. 🔍 **Scrutiny**: RO verifies all nominations\n6. 🔙 **Withdrawal**: Last chance to pull out; final list published\n\n**Phase 4 — Campaign**\n7. 📣 **Campaigning**: Rallies, ads, door-to-door — stops 48hrs before polling\n\n**Phase 5 — Voting**\n8. 🗳️ **Polling Day**: Voters cast votes on EVMs at assigned booths\n\n**Phase 6 — Results**\n9. 🔢 **Counting**: Postal ballots first, then EVM rounds\n10. 🏆 **Results**: Winner declared; majority party forms government" },
  { keywords: ["campaign", "rally", "advertisement", "campaigning rules", "expenditure limit", "spending"], answer: "**Election Campaigning Rules**:\n\n• Campaigning must **stop 48 hours** before polling day (\"silence period\")\n• **Expenditure Limits** (as of 2024):\n  - Lok Sabha: ₹95 lakh (larger states) / ₹75 lakh (smaller states)\n  - Vidhan Sabha: ₹40 lakh (larger) / ₹28 lakh (smaller)\n• Candidates must maintain **daily expenditure accounts**\n• **Prohibited**: Appealing on caste/religion, bribing voters, using government vehicles\n• **Paid news** is treated as an electoral offence\n• Social media campaigns are monitored by ECI's **Media Certification & Monitoring Committee**\n• Star campaigners' travel expenses are exempted from candidate limits\n• **Flying squads** and **surveillance teams** monitor cash, liquor, and gifts distribution" },
  { keywords: ["counting", "count", "result day", "how votes counted", "counting process"], answer: "**Vote Counting Process**:\n\n• Counting happens on a **designated date** (usually 3-4 days after final polling phase)\n• Location: Counting centres set up in each constituency under heavy security\n\n**Step-by-step**:\n1. **Postal ballots** counted first (service voters, senior citizens, PwD)\n2. **EVM counting** starts — Control Units opened round by round\n3. Each round covers votes from a set of booths\n4. **Trends updated** on ECI website in real-time\n5. **VVPAT verification**: Paper slips of **5 randomly selected booths** per constituency are matched with EVM data\n6. **Returning Officer** tallies all rounds and declares the winner\n7. Results uploaded to **results.eci.gov.in**\n\n• Counting agents of all candidates are present to observe\n• Any discrepancy triggers a recount or investigation" },
  { keywords: ["government formation", "form government", "majority", "coalition", "alliance", "who becomes pm", "chief minister"], answer: "**Government Formation After Elections**:\n\n**At the Centre (Lok Sabha)**:\n• Party/alliance winning **272+ seats** (simple majority of 543) is invited by the **President** to form government\n• The **leader of the majority party** becomes **Prime Minister**\n• If no party gets 272, the **largest party/alliance** is invited first\n• The PM must prove majority on the floor of the House within a given time (floor test)\n• **Coalition governments** are common — multiple parties form an alliance\n\n**At the State (Vidhan Sabha)**:\n• The **Governor** invites the majority party leader to become **Chief Minister**\n• Same rules apply — must prove majority via floor test\n• If no clear majority, the Governor uses discretion to invite the party most likely to form a stable government" },
  { keywords: ["governor", "role of governor", "president role", "constitutional head"], answer: "**Role of President & Governor in Elections**:\n\n**President of India**:\n• Dissolves the Lok Sabha on PM's advice, triggering fresh elections\n• Invites the majority party/alliance leader to form government\n• Appoints the Prime Minister\n• Acts on the aid and advice of the Council of Ministers\n\n**Governor (State Level)**:\n• Dissolves the State Assembly on CM's advice\n• Invites majority party leader to form state government\n• Appoints the Chief Minister\n• Can recommend **President's Rule (Article 356)** if no party can form a stable government\n• Administers oath of office to MLAs and the CM\n\nBoth are **constitutional heads** who act on advice, not personal discretion (except in hung assemblies)." },
  { keywords: ["speaker", "whip", "floor test", "trust vote", "no confidence"], answer: "**Speaker, Whip & Floor Tests**:\n\n**Speaker of Lok Sabha**:\n• Elected by MPs after a new Lok Sabha is constituted\n• Presides over parliamentary sessions\n• Has the **casting vote** in case of a tie\n• Decides anti-defection cases under the Tenth Schedule\n• Is expected to be non-partisan once elected\n\n**Whip**:\n• A party official who ensures party members **vote according to party line**\n• Issues a **whip** (directive) instructing members how to vote\n• Violating a **three-line whip** can lead to disqualification under the Anti-Defection Law\n\n**Floor Test (Trust Vote)**:\n• A vote on the floor of the House to prove the government has majority support\n• Can be ordered by the President/Governor\n• If the government loses, the PM/CM must resign" },
  { keywords: ["reservation", "sc st", "obc", "women reservation", "reserved seats", "quota"], answer: "**Reservation in Elections**:\n\n**In Parliament & State Assemblies**:\n• **84 Lok Sabha seats** reserved for Scheduled Castes (SC)\n• **47 Lok Sabha seats** reserved for Scheduled Tribes (ST)\n• Proportional reservation in each state assembly\n• Only candidates from SC/ST communities can contest in reserved constituencies\n• **All voters** in a reserved constituency can vote — it's the candidacy that's reserved, not the electorate\n\n**In Panchayats & Municipalities (73rd/74th Amendments)**:\n• **1/3 seats reserved for women** (including within SC/ST quota)\n• Seats reserved for SC/ST based on their population proportion\n• **OBC reservation** in local body elections in several states\n• Some states have **50% reservation for women** in panchayats (e.g., Bihar, Rajasthan)\n\n**Women's Reservation Act 2023 (106th Amendment)**:\n• Reserves 1/3 seats for women in Lok Sabha & State Assemblies\n• To be implemented after the next Census & delimitation exercise" },
  { keywords: ["booth", "polling station", "polling booth", "booth management", "how booth works"], answer: "**Polling Booth Operations**:\n\n**Setup**:\n• Booths set up in schools, community halls, government buildings\n• Each booth serves **up to 1,500 voters**\n• India has **10.5 lakh+ polling stations** (2024)\n• Every booth within **2 km** of voters' homes\n\n**Booth Staff**:\n• **Presiding Officer**: Overall in-charge of the booth\n• **3 Polling Officers**: Handle voter verification, ink marking, EVM operation\n• **Micro-observers**: Appointed by ECI to watch proceedings\n\n**On Polling Day**:\n1. **Mock poll** conducted before voting starts (with agents present)\n2. EVM sealed after mock poll; counting reset to zero\n3. Voting hours: typically **7 AM to 6 PM**\n4. Voter's identity verified → ink applied → vote cast on EVM\n5. After voting ends, EVM sealed in presence of candidates' agents\n6. EVMs transported to **strong room** under armed guard & CCTV" },
  { keywords: ["ink", "indelible ink", "finger", "mark", "ink mark"], answer: "**Indelible Ink in Indian Elections**:\n\n• Applied on the **left index finger** (nail & surrounding skin) of every voter after they cast their vote\n• **Purpose**: Prevents duplicate voting (a voter cannot vote again at another booth)\n• The ink is manufactured exclusively by **Mysore Paints & Varnish Limited (MPVL)** — the sole authorized supplier since 1962\n• Contains **silver nitrate** — reacts with skin proteins and lasts **2-4 weeks**\n• Cannot be removed by soap, detergent, or any common chemical\n• The ink is exported to **25+ countries** for their elections\n• It's applied using a **felt-tip applicator** dabbed in the ink bottle\n• Election officials at each booth receive exactly measured quantities" },
  { keywords: ["election dispute", "petition", "challenge result", "election tribunal", "court"], answer: "**Election Disputes & Petitions**:\n\n• A **defeated candidate or voter** can challenge election results through an **Election Petition**\n• Must be filed within **45 days** of the result declaration\n\n**Grounds for challenging**:\n• Corrupt practices (bribery, undue influence, religious/caste appeals)\n• Improper acceptance/rejection of nominations\n• Non-compliance with the Constitution or election laws\n• Booth capturing or electoral fraud\n\n**Where to file**:\n• **High Court** for Lok Sabha & Vidhan Sabha elections\n• **Supreme Court** for Presidential & VP elections\n\n• If upheld, the court can **set aside the election** and order a re-poll\n• **No appeal** from High Court orders except to the Supreme Court\n• The Representation of the People Act, 1951 governs all election disputes" },
  { keywords: ["national party", "state party", "political party", "party recognition", "symbol allotment"], answer: "**Political Party Recognition in India**:\n\n**National Party** (currently 6 recognized):\n• Must win **2% of total Lok Sabha seats** (11 seats) from at least 3 states, OR\n• Secure **6% votes in 4+ states** AND win 4 Lok Sabha seats, OR\n• Be recognized as a State Party in **4+ states**\n• Gets a **permanent symbol** valid across India\n\n**State Party**:\n• Must win **3% of total seats** OR **3 seats** in the state assembly, OR\n• Win **1 Lok Sabha seat per 25 allotted** to the state, OR\n• Secure **6% of votes** in the state and win 1 Lok Sabha/2 assembly seats\n\n**Registered Unrecognized Parties**: Can contest but get **free symbols** (not permanent)\n\n• ECI reviews recognition status after every general election\n• Benefits of recognition: free broadcast time on DD/AIR, party symbol, tax exemption" },
  { keywords: ["election expenditure", "money", "cost", "how much election cost", "budget"], answer: "**Cost of Indian Elections**:\n\n• The **2024 Lok Sabha election** is estimated to have cost **₹1.35 lakh crore** ($16.5 billion) — making it the most expensive election in world history\n• This includes spending by ECI, political parties, and candidates\n\n**ECI's Budget**:\n• ECI's official expenditure for 2024: ~₹10,000 crore\n• Covers: EVM deployment, security, logistics, staff, training\n\n**Party & Candidate Spending**:\n• Candidate limits: ₹75-95 lakh (Lok Sabha), ₹28-40 lakh (Assembly)\n• Parties can spend **unlimited amounts** (but must report to ECI)\n• In reality, actual spending far exceeds official limits\n\n**Free Entitlements from ECI**:\n• Free broadcast time on Doordarshan & AIR for recognized parties\n• Free copies of electoral rolls\n• Free supply of voter slips" },
  { keywords: ["nri", "overseas", "abroad", "non resident", "foreign voter"], answer: "**NRI Voting Rights**:\n\n• **NRI voters** can vote in Indian elections since **2011** (amendment to Section 20A of the RP Act)\n• Must be an Indian citizen with a valid passport\n• Can register in the constituency mentioned in their passport\n• **Current requirement**: Must be **physically present** at the polling booth on election day — no postal or online voting for NRIs yet\n• **Proposed changes**: Government has been considering **e-postal ballots** and **proxy voting** for NRIs\n• The **Proxy Voting Bill** was passed in Lok Sabha (2018) but lapsed in Rajya Sabha\n• NRIs must register through **Form 6A** on the NVSP portal\n• Estimated **1.3 crore+ NRI voters** are eligible but turnout remains very low due to travel requirements" },
  { keywords: ["one nation one election", "simultaneous", "all elections together"], answer: "**One Nation One Election**:\n\n• A proposal to hold **Lok Sabha and all State Assembly elections simultaneously**\n• Currently, elections happen at different times across states, creating a \"permanent election mode\"\n\n**Arguments For**:\n• Reduces election expenditure significantly\n• Governance improves — less time in MCC mode\n• Reduces burden on security forces and administrative machinery\n• Voters benefit from reduced disruption\n\n**Arguments Against**:\n• Undermines federalism — state issues overshadowed by national narratives\n• Constitutional amendments needed (Articles 83, 85, 172, 174, 356)\n• Logistically very complex — requires 3x more EVMs and VVPATs\n• If a government falls mid-term, the cycle breaks\n\n• A **High-Level Committee** headed by former President Ram Nath Kovind recommended implementation in **2 phases** (2024 report)\n• Requires ratification by **at least 50% of state legislatures**" },
  { keywords: ["repolling", "re-election", "booth capture", "rigging", "fraud", "malpractice"], answer: "**Repolling & Electoral Malpractice**:\n\n**When ECI Orders Repolling**:\n• Booth capturing (armed groups seize control of booths)\n• EVM malfunction or tampering\n• Natural disasters disrupting voting\n• Serious violations of election law at specific booths\n• Intimidation or violence preventing free voting\n\n**ECI's Powers to Combat Fraud**:\n• Can **postpone, cancel, or countermand** elections\n• Deploys **Central Armed Police Forces (CAPF)** — CRPF, BSF, CISF\n• Uses **webcasting** from sensitive booths (live video monitoring)\n• **Vulnerability mapping** of booths — Extra security at critical/sensitive booths\n• **Voter helpline 1950** for complaints\n• **cVIGIL app** — Citizens can upload photos/videos of violations in real-time\n\n**Penalties**:\n• Booth capturing: imprisonment up to **3 years** + fine\n• Bribery: up to **1 year** imprisonment\n• False declaration in nomination: up to **1 year** imprisonment" },
  { keywords: ["oath", "swearing in", "after election", "new government", "first session"], answer: "**After Elections — Government Formation Steps**:\n\n1. **Results declared** by ECI; winning party/alliance identified\n2. **President/Governor** invites majority leader to form government\n3. **Oath of Office**: PM/CM takes oath at Rashtrapati Bhavan/Raj Bhavan\n4. **Council of Ministers** appointed and sworn in\n5. **Portfolio allocation**: PM/CM assigns ministries\n6. **First session of Parliament/Assembly** convened\n7. **President's Address / Governor's Address** outlines the government's agenda\n8. **Floor Test**: Government proves majority (if demanded by opposition or ordered)\n9. **Speaker elected** by voice vote / division\n10. **Regular governance** begins — Question Hour, debates, bill introduction\n\n• The entire process from results to swearing-in typically takes **3-7 days**\n• The new PM/CM usually takes oath within **48-72 hours** of results" }
];
